Spring cleaning
* Clean up directories
* Create Allwmake scripts
* Create aliases

TO DO: Document changes in CONTENT.md

diff --git a/src/Allwmake b/src/Allwmake
--- a/src/Allwmake
+++ b/src/Allwmake
@@ -5,8 +5,8 @@ cd ${0%/*} || exit 1    # Run from this directory
 . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
 
 # Perform various checks
-wmakeCheckPwd "$WM_TS_PROJECT_DIR" || {
-    echo "Allwmake error: Current directory is not \$WM_TS_PROJECT_DIR"
+wmakeCheckPwd "$WM_TS_SRC_DIR" || {
+    echo "Allwmake error: Current directory is not \$WM_TS_SRC_DIR"
     echo "    The environment variables are inconsistent with the installation."
     echo "    Check the OpenFOAM entries in your dot-files and source them."
     exit 1
@@ -18,10 +18,8 @@ wmakeCheckPwd "$WM_TS_PROJECT_DIR" || {
     exit 1
 }
 
-# Compile libtoolShed libraries
-src/Allwmake $targetType $*
 
-# Compile libtoolShed applications
-applications/Allwmake $targetType $*
+wmake $targetType fvPatchFields
+
 
 #------------------------------------------------------------------------------
